import localFont from "next/font/local";
import "./globals.css";
// pages/_app.js or wherever your global imports are
import '@fortawesome/fontawesome-free/css/all.min.css';

import Head from 'next/head';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <Head>
      <script
          src="https://kit.fontawesome.com/7057a291ca.js"
          crossOrigin="anonymous"
          async
        ></script>

        
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
